#!/sbin/openrc-run

pidfile=/var/run/${SVCNAME}.pid

depend() {
	need net
}

start() {
	ebegin "Starting ${SVCNAME}"
	source "/etc/pypiserver.conf"
	pypiserver_opts=(
		--interface ${PYPISERVER_INTERFACE}
		--port ${PYPISERVER_PORT}
		${PYPISERVER_ADDITIONAL_OPTIONS}
		${PYPISERVER_PACKAGES}
	)
	start-stop-daemon --start --user pypiserver --group pypiserver --chdir /var/lib/pypiserver/ --exec /usr/bin/pypi-server --background --make-pidfile --pidfile ${pidfile} --stdout ${PYPISERVER_LOGFILE} --stderr ${PYPISERVER_LOGFILE} -- ${pypiserver_opts[*]}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/bin/pypi-server --pidfile $pidfile
	eend $?
}
