#!/sbin/openrc-run

logfile=/var/log/laminard
pidfile=/var/run/laminard.pid

depend() {
	need net
}

start() {
	ebegin "Starting ${SVCNAME}"
	source "/etc/laminar.conf"
	laminar_opts=(
		$(test -n "$LAMINAR_HOME" && echo --env=LAMINAR_HOME="$LAMINAR_HOME")
		$(test -n "$LAMINAR_BIND_HTTP" && echo --env=LAMINAR_BIND_HTTP="$LAMINAR_BIND_HTTP")
		$(test -n "$LAMINAR_BIND_RPC" && echo --env=LAMINAR_BIND_RPC="$LAMINAR_BIND_RPC")
		$(test -n "$LAMINAR_TITLE" && echo --env=LAMINAR_TITLE="$LAMINAR_TITLE")
		$(test -n "$LAMINAR_KEEP_RUNDIRS" && echo --env=LAMINAR_KEEP_RUNDIR="$LAMINAR_KEEP_RUNDIRS")
		$(test -n "$LAMINAR_ARCHIVE_URL" && echo --env=LAMINAR_ARCHIVE_URL="$LAMINAR_ARCHIVE_URL")
	)
	touch $logfile
	chmod g+w $logfile
	chgrp laminar $logfile
	start-stop-daemon --start --user laminar --group $LAMINAR_GROUP --exec /usr/bin/laminard --background --make-pidfile --pidfile $pidfile --stdout $logfile --stderr $logfile ${laminar_opts[*]}
	laminar_http_socket=${LAMINAR_BIND_HTTP#unix:}
	if [ -e $laminar_http_socket ]; then
		chgrp $LAMINAR_GROUP $laminar_http_socket
		chmod g+w $laminar_http_socket
	fi
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/bin/laminard --pidfile $pidfile
	eend $?
}
