#!/sbin/openrc-run

logfile=/var/log/laminar/${SVCNAME}.log
pidfile=/var/run/${SVCNAME}.pid

depend() {
	need net
}

start() {
	ebegin "Starting ${SVCNAME}"
	source "/etc/laminar.conf"
	laminar_opts=(
		$(test -n "$LAMINAR_HOME" && echo --env=LAMINAR_HOME="$LAMINAR_HOME")
		$(test -n "$LAMINAR_BIND_HTTP" && echo --env=LAMINAR_BIND_HTTP="$LAMINAR_BIND_HTTP")
		$(test -n "$LAMINAR_BIND_RPC" && echo --env=LAMINAR_BIND_RPC="$LAMINAR_BIND_RPC")
		$(test -n "$LAMINAR_TITLE" && echo --env=LAMINAR_TITLE="$LAMINAR_TITLE")
		$(test -n "$LAMINAR_KEEP_RUNDIRS" && echo --env=LAMINAR_KEEP_RUNDIRS="$LAMINAR_KEEP_RUNDIRS")
		$(test -n "$LAMINAR_ARCHIVE_URL" && echo --env=LAMINAR_ARCHIVE_URL="$LAMINAR_ARCHIVE_URL")
	)
	start-stop-daemon --start --user laminar --group laminar --exec /usr/sbin/laminard --background --make-pidfile --pidfile $pidfile --stdout $logfile --stderr $logfile ${laminar_opts[*]}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/bin/laminard --pidfile $pidfile
	eend $?
}
